### ISSUE TITLE
Add visible (but perhaps transparent) layer?

### ISSUE THREAD

**Issue by djinnome** [frankkramer-lab/mully#4]
This is more of a feature request or nice-to-have.  One thing that really helps (static) 3d images pop is when you add a transparent (but visible) layer, like what you did for the Mully logo or such as in figures 1, 2, 3, and 4 in the manuscript. I can see how in a rotatable 3d image that node size provides depth, but I wonder if it would also be possible to (perhaps optionally) visualize the layer that the nodes are associated with.

If it is easy to mock up, then great, but if not, no worries. I just thought it might be a helpful way for the user to visualize her data.

**Comment by zaynabhammoud** [comment]
Thank you for the suggestion. I struggled with this for a long time when I was writing the visualization functions, and what I was trying to do, is to draw a rectangle/parallelogram around the nodes to represent a layer form, but I couldn't get a satisfying result, that's why I decided to move on with other features then get back to that after I finish the implementation.

**Comment by zaynabhammoud** [comment]
@djinnome Thank you again for your suggestion. I just uploaded the new version of mully with visible layers added, as well as different graphics that can be controlled in the 3D visualization.
